
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action addActionA;
	private global::Gtk.Action cancelAction;
	private global::Gtk.Action editActionA;
	private global::Gtk.Action refreshActionA;
	private global::Gtk.Action refreshActionC;
	private global::Gtk.Action addActionC;
	private global::Gtk.Action deleteActionC;
	private global::Gtk.Action editActionC;
	private global::Gtk.Action deleteActionA;
	private global::Gtk.Notebook notebook;
	private global::Gtk.VBox vBox;
	private global::Gtk.Toolbar toolbar2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.ComboBox comboboxA;
	private global::Gtk.ComboBox comboboxA1;
	private global::Gtk.Entry entryA;
	private global::Gtk.Button buttonA;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeViewA;
	private global::Gtk.Label labelArticulo;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Toolbar toolbar3;
	private global::Gtk.HBox hbox3;
	private global::Gtk.ComboBox comboboxC;
	private global::Gtk.ComboBox comboboxC1;
	private global::Gtk.Entry entryC;
	private global::Gtk.Button buttonC;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView treeViewC;
	private global::Gtk.Label labelCategoria;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.addActionA = new global::Gtk.Action ("addActionA", null, null, "gtk-add");
		w1.Add (this.addActionA, null);
		this.cancelAction = new global::Gtk.Action ("cancelAction", null, null, "gtk-cancel");
		w1.Add (this.cancelAction, null);
		this.editActionA = new global::Gtk.Action ("editActionA", null, null, "gtk-edit");
		w1.Add (this.editActionA, null);
		this.refreshActionA = new global::Gtk.Action ("refreshActionA", null, null, "gtk-refresh");
		w1.Add (this.refreshActionA, null);
		this.refreshActionC = new global::Gtk.Action ("refreshActionC", null, null, "gtk-refresh");
		w1.Add (this.refreshActionC, null);
		this.addActionC = new global::Gtk.Action ("addActionC", null, null, "gtk-add");
		w1.Add (this.addActionC, null);
		this.deleteActionC = new global::Gtk.Action ("deleteActionC", null, null, "gtk-delete");
		w1.Add (this.deleteActionC, null);
		this.editActionC = new global::Gtk.Action ("editActionC", null, null, "gtk-edit");
		w1.Add (this.editActionC, null);
		this.deleteActionA = new global::Gtk.Action ("deleteActionA", null, null, "gtk-delete");
		w1.Add (this.deleteActionA, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook = new global::Gtk.Notebook ();
		this.notebook.CanFocus = true;
		this.notebook.Name = "notebook";
		this.notebook.CurrentPage = 1;
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.vBox = new global::Gtk.VBox ();
		this.vBox.Name = "vBox";
		this.vBox.Spacing = 6;
		// Container child vBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='refreshActionA' action='refreshActionA'/><toolitem name='addActionA' action='addActionA'/><toolitem name='deleteActionA' action='deleteActionA'/><toolitem name='editActionA' action='editActionA'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.vBox.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vBox [this.toolbar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vBox.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.comboboxA = global::Gtk.ComboBox.NewText ();
		this.comboboxA.Name = "comboboxA";
		this.hbox1.Add (this.comboboxA);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.comboboxA]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.comboboxA1 = global::Gtk.ComboBox.NewText ();
		this.comboboxA1.Name = "comboboxA1";
		this.hbox1.Add (this.comboboxA1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.comboboxA1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entryA = new global::Gtk.Entry ();
		this.entryA.CanFocus = true;
		this.entryA.Name = "entryA";
		this.entryA.IsEditable = true;
		this.entryA.InvisibleChar = '•';
		this.hbox1.Add (this.entryA);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryA]));
		w5.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonA = new global::Gtk.Button ();
		this.buttonA.CanFocus = true;
		this.buttonA.Name = "buttonA";
		this.buttonA.UseUnderline = true;
		this.buttonA.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
		this.hbox1.Add (this.buttonA);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonA]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		this.vBox.Add (this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vBox [this.hbox1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vBox.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeViewA = new global::Gtk.TreeView ();
		this.treeViewA.CanFocus = true;
		this.treeViewA.Name = "treeViewA";
		this.GtkScrolledWindow.Add (this.treeViewA);
		this.vBox.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vBox [this.GtkScrolledWindow]));
		w9.Position = 2;
		this.notebook.Add (this.vBox);
		// Notebook tab
		this.labelArticulo = new global::Gtk.Label ();
		this.labelArticulo.Name = "labelArticulo";
		this.labelArticulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Articulo");
		this.notebook.SetTabLabel (this.vBox, this.labelArticulo);
		this.labelArticulo.ShowAll ();
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar3'><toolitem name='refreshActionC' action='refreshActionC'/><toolitem name='addActionC' action='addActionC'/><toolitem name='deleteActionC' action='deleteActionC'/><toolitem name='editActionC' action='editActionC'/></toolbar></ui>");
		this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar3")));
		this.toolbar3.Name = "toolbar3";
		this.toolbar3.ShowArrow = false;
		this.hbox2.Add (this.toolbar3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.toolbar3]));
		w11.Position = 0;
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.comboboxC = global::Gtk.ComboBox.NewText ();
		this.comboboxC.Name = "comboboxC";
		this.hbox3.Add (this.comboboxC);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.comboboxC]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.comboboxC1 = global::Gtk.ComboBox.NewText ();
		this.comboboxC1.Name = "comboboxC1";
		this.hbox3.Add (this.comboboxC1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.comboboxC1]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entryC = new global::Gtk.Entry ();
		this.entryC.CanFocus = true;
		this.entryC.Name = "entryC";
		this.entryC.IsEditable = true;
		this.entryC.InvisibleChar = '•';
		this.hbox3.Add (this.entryC);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entryC]));
		w15.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.buttonC = new global::Gtk.Button ();
		this.buttonC.CanFocus = true;
		this.buttonC.Name = "buttonC";
		this.buttonC.UseUnderline = true;
		this.buttonC.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
		this.hbox3.Add (this.buttonC);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonC]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox4.Add (this.hbox3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeViewC = new global::Gtk.TreeView ();
		this.treeViewC.CanFocus = true;
		this.treeViewC.Name = "treeViewC";
		this.GtkScrolledWindow1.Add (this.treeViewC);
		this.vbox4.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
		w19.Position = 2;
		this.notebook.Add (this.vbox4);
		global::Gtk.Notebook.NotebookChild w20 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.vbox4]));
		w20.Position = 1;
		// Notebook tab
		this.labelCategoria = new global::Gtk.Label ();
		this.labelCategoria.Name = "labelCategoria";
		this.labelCategoria.LabelProp = global::Mono.Unix.Catalog.GetString ("Categoria");
		this.notebook.SetTabLabel (this.vbox4, this.labelCategoria);
		this.labelCategoria.ShowAll ();
		this.Add (this.notebook);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.addActionA.Activated += new global::System.EventHandler (this.OnAddActionAActivated);
		this.editActionA.Activated += new global::System.EventHandler (this.OnEditActionAActivated);
		this.refreshActionA.Activated += new global::System.EventHandler (this.OnRefreshActionAActivated);
		this.refreshActionC.Activated += new global::System.EventHandler (this.OnRefreshActionCActivated);
		this.addActionC.Activated += new global::System.EventHandler (this.OnAddActionCActivated);
		this.deleteActionC.Activated += new global::System.EventHandler (this.OnDeleteActionCActivated);
		this.editActionC.Activated += new global::System.EventHandler (this.OnEditActionCActivated);
		this.deleteActionA.Activated += new global::System.EventHandler (this.OnDeleteActionAActivated);
		this.buttonA.Clicked += new global::System.EventHandler (this.OnButtonAClicked);
		this.buttonC.Clicked += new global::System.EventHandler (this.OnButtonCClicked);
	}
}
